### ISSUE TITLE
How to configure SSL settings for authenticated cloudlflare origin pulls

### ISSUE THREAD

**Issue by mfjonesy** [jlesage/docker-nginx-proxy-manager#23]
This docker is working perfectly on Unraid but I have a question on how to secure it using Cloudflare. Right now I'm using Cloudflare in front of my sites but I'd like to secure it as much as possible. I was looking through their security settings and noticed you can enable authenticated origin pulls. I'm trying to follow these instructions they have posted for nginx:

"For authenticated origin pulls to work, use Full SSL in the Cloudflare Crypto app, and update the origin web server SSL configuration. Download origin-pull-ca.pem and place the certificate in a file on your origin web server, for example in /etc/nginx/certs/cloudflare.crt
Then add these lines to the SSL configuration for your origin web server:

    ssl_client_certificate /etc/nginx/certs/cloudflare.crt;
    ssl_verify_client on;"

However I'm not sure where to place the file that contains the origin-pull-ca.pem or where to edit the SSL configuration to add those last two lines. I really have no idea what I'm doing so is this even possible with this docker? Thanks for the amazing docker!

**Comment by jlesage** [comment]
I'm not familiar with Cloudflare features, but it seems that you need to install custom certificates.  This means that in NginxProxyManager, instead of using Letsencrypt certificates, install the one from Cloudflare: access the `SSL Certificates` page.  Then, click the `Add SSL certificate` button and then `Custom`.
Once installed, you can use this certificate in a `Proxy Host` configuration.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
