### ISSUE TITLE
Issue - Internal Error - Host Status Unknown

### ISSUE THREAD

**Issue by ansred** [jlesage/docker-nginx-proxy-manager#247]
Issue:
Issue - Internal Error - Host Status Unknown

NPN Version:
v2.9.16 

Docker Host:
Synology DSM

Issue Sreenshot:
<img width="861" alt="Screen Shot 2022-03-22 at 8 35 09 AM" src="https://user-images.githubusercontent.com/5244872/159487595-1960663e-4d25-4d75-acb9-ae75e88c7201.png">

Details:
Issue started today suddently with no changes on NPM, just wanted to the change the protocol from http to https and then I got this internal error and status showing as uknwon

I can't delete the host (Still works though!)

Another note:
I tried to change the host protocol from the host config file manually, however, no luck, still the issue persists and now the Proxy host # changed from 18 to 92

Both hosts don't exists in the /data folder.

Any ideas?!

**Comment by hackmannbr** [comment]
I had same problem....

Dont know why... what I did to fix it was disable the host and enable again... got it online again....

Even in unknown status it never stop working, like you said... 

It is happening often when I have to update the ssl certificate... I am also using a custom code since I am using Authelia.... 

Just did that (disable and enable host) and got the green light.

Cheerz.

**Comment by wilotas** [comment]
Hi friends, 

I have the same case. I have 15 hosts "Online".

If i edit anyone of them and save it (althoug I dont change anything) I receive an "Internal Error" and Status gos to "Unknown". Hosts continue working anyway.

Any info about it?

**Comment by ansred** [comment]
I just wiped the entire instance and re do it with the official image using sqlite database, since then, everything been working fine.
